import os

SOURCE_PURVIEW_ACCOUNT_NAME = os.environ['SOURCE_PURVIEW_ACCOUNT_NAME']
SOURCE_COLLECTION_COMMA_SEPARATED = os.environ['SOURCE_COLLECTION_COMMA_SEPARATED']
TARGET_PURVIEW_ACCOUNT_NAME = os.environ['TARGET_PURVIEW_ACCOUNT_NAME']
METADATA_WRITE_BLOB_ACCOUNT = os.environ['METADATA_WRITE_BLOB_ACCOUNT']
METADATA_WRITE_BLOB_CONTAINER = os.environ['METADATA_WRITE_BLOB_CONTAINER']
METADATA_WRITE_BLOB_DIRECTORY = os.environ['METADATA_WRITE_BLOB_DIRECTORY']
METADATA_READ_BLOB_ACCOUNT = os.environ['METADATA_READ_BLOB_ACCOUNT']
METADATA_READ_BLOB_CONTAINER = os.environ['METADATA_READ_BLOB_CONTAINER']
METADATA_READ_BLOB_DIRECTORY = os.environ['METADATA_READ_BLOB_DIRECTORY']
METADATA_CAPTURE_CRON = os.environ['METADATA_CAPTURE_CRON']
METADATA_PUBLISH_CRON = os.environ['METADATA_PUBLISH_CRON']
TARGET_COLLECTION_NAME = os.environ['TARGET_COLLECTION_NAME']